### ISSUE TITLE
[BUG] Unable to launch MC after failed mod update (Windows)

### ISSUE THREAD

**Issue by Felix14-v2** [ModManagerMC/ModManager#137] opened 2022-02-13 18:48 UTC
**Description**
After unsuccessfully downloading new versions of the mod, you may get an error and the update will fail. However, an empty file of the new mod will be created, which will lead to an error loading mods (see screenshots).

**To Reproduce**
1. Install outdated version of some mod
2. Make ModManager get an error when updating it (I don't know if it's possible to do this on purpose. But in my case it was not possible to update the Fabric API and Amecs)
3. Close the game
4. Try to launch MC with empty mod(s) files
5. See the error

**Expected behavior**
ModManager should delete empty mod files when they failed to download.

**Technical Info**
 - Windows 10
 - Minecraft 1.18.1
 - Fabric Loader 0.13.1
 - ModManager 1.2.2

**Logs**
[latest.log](https://github.com/DeathsGun/ModManager/files/8056394/latest.log)

**Additional context**
Failed updating
[latest.log](https://github.com/DeathsGun/ModManager/files/8056401/latest.log)

<details>
 <summary>
Screenshots
</summary>

Updating error
![image](https://user-images.githubusercontent.com/75726196/153769099-abe1ab84-96e2-423a-b5fb-9a87395bbee6.png)

Empty mod files created by MM after failed mod update
![image](https://user-images.githubusercontent.com/75726196/153768971-2988c51d-20f3-48e8-ba2b-f9d9cc234131.png)

Fabric error screen
![image](https://user-images.githubusercontent.com/75726196/153769951-7afd108a-e909-4310-8747-b63df013412e.png)
<details>
 <summary>Error text</summary>
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:137)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:137)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:208)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\Александр\AppData\Roaming\.minecraft\home\Fabric 1.18\mods\fabric-api-0.46.4+1.18.jar]: java.util.zip.ZipException: zip file is empty
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:134)
	... 5 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\Александр\AppData\Roaming\.minecraft\home\Fabric 1.18\mods\fabric-api-0.46.4+1.18.jar]: java.util.zip.ZipException: zip file is empty
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:194)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:262)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:232)
	... 7 more

</details>

</details>

**Comment by DeathsGun** [comment] 2022-03-02 11:08
Looks like a duplicate of #139 further discussion will be over there

**Closed** 2022-03-02 11:08 UTC
Labels: bug, duplicate
